In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
weather_df=pd.read_csv("data/weather_master.csv")

In [5]:
weather_df.head()

,Unnamed: 0,Unnamed: 0.1,STN,mo,da,temp,min,max,stp,slp,...,lat,lon,elev,rh,ah,day_from_jan_first,Distance,country,lat_st,long_st
0,0,1419,724550-13947,1,10,34.4,24.6,41.7,975.7,NaN,...,39.05,-96.767,324.6,0.746709,0.816725,10,0.275588,US,39.05,-96.767
1,1,1506,724550-13947,4,20,58.6,46.6,72.9,972.6,1010.5,...,39.05,-96.767,324.6,0.515454,0.127481,111,0.275588,US,39.05,-96.767
2,2,1507,724550-13947,6,4,79.2,63.9,92.8,970.3,1007.3,...,39.05,-96.767,324.6,0.700291,0.199198,156,0.275588,US,39.05,-96.767
3,3,3197,724550-13947,4,17,38.3,32.9,50.9,982.1,1021.2,...,39.05,-96.767,324.6,0.735294,0.357553,108,0.275588,US,39.05,-96.767
4,4,136793,724550-13947,6,29,82.7,78.6,87.6,965.7,1002.3,...,39.05,-96.767,324.6,0.696544,0.207042,181,0.275588,US,39.05,-96.767

In [12]:
temp=weather_df[["country","long_st","lon"]]

In [13]:
temp.drop_duplicates()

                    country  long_st      lon
0                        US  -96.767  -96.767
181                      US -104.817 -104.817
362     Antigua and Barbuda  -63.115  -63.115
543                      US  -95.778  -95.778
724                Honduras  -81.755  -81.755
905                      US  -96.820  -96.820
1086                     US  -92.150  -92.150
1267                     US  -81.590  -81.590
1448                     US -106.474 -106.474
1629              Argentina  -61.350  -61.350
1630                Bolivia  -61.350  -61.350
1631                 Brazil  -61.350  -61.350
1632                  Chile  -61.350  -61.350
1633                 Guyana  -61.350  -61.350
1634               Paraguay  -61.350  -61.350
1635               Suriname  -61.350  -61.350
1636    Trinidad and Tobago  -61.350  -61.350
1637                Uruguay  -61.350  -61.350
3258                     US -157.096 -157.096
3439                     US  -92.156  -92.156
3620                 Canada  -69.533  -69.533
3801                     US  -97.683  -97.683
3982                     US  -99.478  -99.478
4163                 Canada -105.210 -105.210
4344                     US -110.290 -110.290
4525                     US  -86.979  -86.979
4706                 Canada  -67.883  -67.883
4707                Estonia  -67.883  -67.883
4708                Finland  -67.883  -67.883
4709              Greenland  -67.883  -67.883
...                     ...      ...      ...
30833                  Oman  134.544  134.544
30834              Pakistan  134.544  134.544
30835           Philippines  134.544  134.544
30836                 Qatar  134.544  134.544
30837               Reunion  134.544  134.544
30838                Russia  134.544  134.544
30839          Saudi Arabia  134.544  134.544
30840            Seychelles  134.544  134.544
30841             Singapore  134.544  134.544
30842               Somalia  134.544  134.544
30843             Sri Lanka  134.544  134.544
30844               Taiwan*  134.544  134.544
30845              Thailand  134.544  134.544
30846  United Arab Emirates  134.544  134.544
30847            Uzbekistan  134.544  134.544
30848               Vietnam  134.544  134.544
45069               Belarus  -67.793  -67.793
45070               Belgium  -67.793  -67.793
45071                Canada  -67.793  -67.793
45074               Czechia  -67.793  -67.793
45075               Germany  -67.793  -67.793
45076              Guernsey  -67.793  -67.793
45077                Jersey  -67.793  -67.793
45078             Lithuania  -67.793  -67.793
45079            Luxembourg  -67.793  -67.793
45080                Poland  -67.793  -67.793
47241                    US  -74.600  -74.600
47422                    US  -94.051  -94.051
47784                    US -151.239 -151.239
47965                    US  -69.797  -69.797

[224 rows x 3 columns]