In this notebook I add weather informations, such as temperature and precipitations, to the training set of the [COVID-19 forecasting competition](https://www.kaggle.com/c/covid19-global-forecasting-week-1/discussion), in order to determine whether there is any correlation with the growth of confirmed cases. Weather data is imported from the [NOAA GSOD dataset](https://www.kaggle.com/noaa/gsod), continuously updated to include recent measurments.

[Data for this and previous weeks is available in dataset form here.](https://www.kaggle.com/davidbnn92/weather-data-for-covid19-data-analysis)

Edit: now missing values are denoted with usual `NaN`s, and not with `9999`s.

Edit 2: information concerning humidity was added, following [brennanmurphy](https://www.kaggle.com/brennanmurphy)'s advice. More specifically, dewpoint temperature was added from the NOAA GSOD dataset, then absolute and relative humidity were computed.

In [1]:
import numpy as np
import pandas as pd

import os
import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.spatial.distance import cdist

for dirname, _, filenames in os.walk('/kaggle/input'):
    print(dirname)

from google.cloud import bigquery

Here is the weather data:
* `temp`: Mean temperature for the day in degrees Fahrenheit to tenths.
* `max`: Maximum temperature reported during the day in Fahrenheit to tenths--time of max temp report varies by country and region, so this will sometimes not be the max for the calendar day.
* `min`: Minimum temperature reported during the day in Fahrenheit to tenths--time of min temp report varies by country and region, so this will sometimes not be the min for the calendar day.
* `stp`: Mean station pressure for the day in millibars to tenths.
* `slp`: Mean sea level pressure for the day in millibars to tenths.
* `dewp`: Mean dew point for the day in degrees Fahrenheit to tenths. 
* `wdsp`: Mean wind speed for the day in knots to tenths.
* `prcp`: Total precipitation (rain and/or melted snow) reported during the day in inches and hundredths; will usually not end with the midnight observation--i.e., may include latter part of previous day. .00 indicates no measurable precipitation (includes a trace).
* `fog`: Indicators (1 = yes, 0 = no/not reported) for the occurrence during the day

In [12]:
def implicit():
    from google.cloud import storage

    # If you don't specify credentials when constructing the client, the
    # client library will look for credentials in the environment.
    storage_client = storage.Client()

    # Make an authenticated API request
    buckets = list(storage_client.list_buckets())
    print(buckets)

In [13]:
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]=r"C:\Users\Jost\Desktop\covid-304dab3f9983.json"

In [18]:
implicit()

[]

In [136]:
client = bigquery.Client()
dataset_ref = client.dataset("noaa_gsod", project="bigquery-public-data")
dataset = client.get_dataset(dataset_ref)

tables = list(client.list_tables(dataset))

table_ref = dataset_ref.table("stations")
table = client.get_table(table_ref)
stations_df = client.list_rows(table).to_dataframe()

table_ref = dataset_ref.table("gsod2020")
table = client.get_table(table_ref)
twenty_twenty_df = client.list_rows(table).to_dataframe()

stations_df['STN'] = stations_df['usaf'] + '-' + stations_df['wban']
twenty_twenty_df['STN'] = twenty_twenty_df['stn'] + '-' + twenty_twenty_df['wban']

cols_1 = ['STN', 'mo', 'da', 'temp', 'min', 'max', 'stp', 'slp', 'dewp', 'wdsp', 'prcp', 'fog']
cols_2 = ['STN', 'country', 'state', 'call', 'lat', 'lon', 'elev']
weather_df = twenty_twenty_df[cols_1].join(stations_df[cols_2].set_index('STN'), on='STN')

weather_df['temp'] = weather_df['temp'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['max'] = weather_df['max'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['min'] = weather_df['min'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['stp'] = weather_df['stp'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['slp'] = weather_df['slp'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['dewp'] = weather_df['dewp'].apply(lambda x: np.nan if x==9999.9 else x)
weather_df['wdsp'] = weather_df['wdsp'].apply(lambda x: np.nan if x==999.9 else x)
weather_df['prcp'] = weather_df['prcp'].apply(lambda x: np.nan if x==99.9 else x)

display(weather_df.tail(10))
weather_df.info(verbose=True)

C:\Users\Jost\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: PyarrowMissingWarning: Converting to a dataframe without pyarrow installed is often slower and will become unsupported in the future. Please install the pyarrow package.
  if __name__ == '__main__':
C:\Users\Jost\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: PyarrowMissingWarning: Converting to a dataframe without pyarrow installed is often slower and will become unsupported in the future. Please install the pyarrow package.
  del sys.path[0]

,STN,mo,da,temp,min,max,stp,slp,dewp,wdsp,prcp,fog,country,state,call,lat,lon,elev
2035575,999999-00379,02,02,36.0,32.0,41.0,989.3,NaN,33.4,4.1,99.99,1,NaN,NaN,NaN,NaN,NaN,NaN
2035576,999999-00379,02,03,43.6,33.8,59.0,992.4,NaN,34.6,4.2,99.99,1,NaN,NaN,NaN,NaN,NaN,NaN
2035577,999999-00379,02,07,40.2,33.8,51.8,975.7,NaN,38.7,6.4,99.99,1,NaN,NaN,NaN,NaN,NaN,NaN
2035578,999999-00379,02,14,33.6,23.0,42.8,6.3,NaN,21.9,9.1,99.99,1,NaN,NaN,NaN,NaN,NaN,NaN
2035579,999999-00379,03,23,37.0,33.8,41.0,15.1,NaN,32.9,6.5,99.99,1,NaN,NaN,NaN,NaN,NaN,NaN
2035580,999999-93804,01,31,36.4,32.0,42.8,994.0,NaN,32.0,2.8,99.99,1,US,SC,SPA,34.917,-81.95,+0244.1
2035581,999999-93804,02,20,41.8,33.8,48.2,998.1,NaN,33.6,4.3,99.99,1,US,SC,SPA,34.917,-81.95,+0244.1
2035582,999999-00421,01,29,35.1,32.5,40.1,4.5,NaN,31.1,4.8,99.99,1,US,KY,None,37.350,-87.40,+0124.4
2035583,999999-00421,02,06,36.4,32.5,38.7,987.7,NaN,32.5,6.9,99.99,1,US,KY,None,37.350,-87.40,+0124.4
2035584,999999-00421,02,07,32.4,30.0,36.3,991.6,NaN,24.4,8.1,99.99,1,US,KY,None,37.350,-87.40,+0124.4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2035585 entries, 0 to 2035584
Data columns (total 18 columns):
STN        object
mo         object
da         object
temp       float64
min        float64
max        float64
stp        float64
slp        float64
dewp       float64
wdsp       object
prcp       float64
fog        object
country    object
state      object
call       object
lat        float64
lon        float64
elev       object
dtypes: float64(9), object(9)
memory usage: 279.5+ MB

Now let's compute absolute and relative humidity from temperature and dew point:

In [137]:
# convert everything into celsius
temp = (weather_df['temp'] - 32) / 1.8
dewp = (weather_df['dewp'] - 32) / 1.8
    
# compute relative humidity as ratio between actual vapour pressure (computed from dewpoint temperature)
# and saturation vapour pressure (computed from temperature) (the constant 6.1121 cancels out)
weather_df['rh'] = (np.exp((18.678*dewp)/(257.14+dewp))/np.exp((18.678*temp)/(257.14+temp)))

# calculate actual vapour pressure (in pascals)
# then use it to compute absolute humidity from the gas law of vapour 
# (ah = mass / volume = pressure / (constant * temperature))
weather_df['ah'] = ((np.exp((18.678*dewp)/(257.14+dewp))) * 6.1121 * 100) / (461.5 * temp)

In [138]:
weather_df.head()

,STN,mo,da,temp,min,max,stp,slp,dewp,wdsp,prcp,fog,country,state,call,lat,lon,elev,rh,ah
0,222130-99999,02,13,31.6,30.4,32.4,975.2,991.7,30.5,4.4,0.03,1,RS,None,None,67.550,33.350,+0134.0,0.956406,-5.608638
1,224130-99999,04,23,28.9,24.8,35.6,1.6,1011.7,18.4,2.9,0.00,1,RS,None,None,65.783,33.933,+0080.0,0.644366,-0.436884
2,225290-99999,04,25,31.6,27.1,37.6,989.3,990.0,25.4,7.3,0.06,1,RS,None,None,64.233,35.883,+0003.0,0.775665,-4.548720
3,228370-99999,02,25,29.3,28.2,30.7,986.4,993.5,21.7,6.8,0.04,1,RS,None,None,61.017,36.450,+0056.0,0.729415,-0.577172
4,228370-99999,04,24,33.7,20.5,40.3,991.5,998.5,26.9,999.9,0.04,1,RS,None,None,61.017,36.450,+0056.0,0.758471,1.138849

In [139]:
weather_df.to_csv("data/weather.csv")

In [2]:
weather_df=pd.read_csv("data/weather.csv")

C:\Users\Jost\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
weather_df.groupby(['STN']).size()

STN
100001-99999     99
100109-9999     180
100149-9999     130
100180-99999    137
100209-9999     180
100309-9999     179
100330-99999    180
100370-99999    180
100380-99999    180
100465-99999    168
100609-9999     179
100709-9999     180
100809-9999     180
100909-9999     141
101009-9999     180
101109-9999     179
101260-99999    180
101360-99999    180
101470-99999    180
101490-99999    177
101509-9999     180
101560-99999    179
101609-9999     179
101709-9999     179
101720-99999    180
101935-99999    135
102009-9999     179
102240-99999    180
102309-9999     180
102409-9999     179
               ...
999999-93245    181
999999-93733    167
999999-93804    181
999999-93816    181
999999-94044    153
999999-94045    153
999999-94059    181
999999-94060    181
999999-94074    181
999999-94075    181
999999-94077    176
999999-94078    181
999999-94079    181
999999-94080    181
999999-94081    181
999999-94082    181
999999-94084    181
999999-94085    181
999999-94088    181
999999-94099    176
999999-94644    181
999999-94645    181
999999-94995    181
999999-94996    181
999999-96404    181
999999-96405    176
999999-96406    181
999999-96407    181
999999-96408    181
999999-96409    181
Length: 12063, dtype: int64

In [4]:
weather_df=weather_df.groupby('STN').filter(lambda x : len(x)>180)

In [5]:
train=pd.read_csv("data/train.csv")
train=train[["Country/Region","Lat","Long"]]
train=train.drop_duplicates()
train=train.rename(columns={"Country/Region":"country"})

train.head()

                 country      Lat     Long
0            Afghanistan  33.0000  65.0000
63               Albania  41.1533  20.1683
126              Algeria  28.0339   1.6596
189              Andorra  42.5063   1.5218
252  Antigua and Barbuda  17.0608 -61.7964

In [6]:
train.groupby('country').filter(lambda x : len(x)>1).country.unique()

array(['Australia', 'Canada', 'China', 'Denmark', 'France', 'Netherlands',
       'US', 'United Kingdom'], dtype=object)

In [7]:
train[train.country=="France"]

     country      Lat      Long
6363  France  46.2276    2.2137
6426  France   3.9339  -53.1258
6489  France -17.6797  149.4068
6552  France  16.2500  -61.5833
6615  France -12.8275   45.1662
6678  France -21.1351   55.2471
6741  France  17.9000  -62.8333
6804  France  18.0708  -63.0501

In [8]:
# Drop if country has mmultiple parts over the world
train=train[(train.country!="United Kingdom") & (train.Lat!=49.3723)]
train=train[(train.country!="Netherlands") & (train.Lat!= 52.1326)]
train=train[(train.country!="Denmark") & (train.Lat!= 56.2639)]
train=train[(train.country!="France") & (train.Lat!= 46.2276)]

In [9]:

weather_df.head()

,Unnamed: 0,STN,mo,da,temp,min,max,stp,slp,dewp,...,prcp,fog,country,state,call,lat,lon,elev,rh,ah
992,992,727675-94011,6,29,67.1,65.7,69.8,939.2,998.2,66.6,...,0.91,1,US,ND,KMIB,48.417,-101.350,508.1,0.982701,0.248996
1037,1037,722164-53949,1,11,39.1,31.5,48.6,985.4,NaN,39.1,...,0.57,1,US,OK,KOKM,35.668,-95.949,219.5,1.000000,0.445230
1264,1264,723146-53892,2,7,40.2,24.6,50.4,886.0,NaN,37.9,...,0.00,1,US,NC,KGEV,36.432,-81.419,969.3,0.913885,0.367770
1303,1303,720539-00165,3,19,34.4,28.4,45.5,761.6,NaN,29.8,...,99.99,1,US,CO,KPSO,37.283,-107.050,2335.1,0.830644,0.908531
1320,1320,720539-00165,1,27,28.2,18.9,38.8,765.9,NaN,26.7,...,99.99,1,US,CO,KPSO,37.283,-107.050,2335.1,0.940128,-0.505296

In [10]:
weather_stations=weather_df[["STN","lat","lon"]]

In [11]:
weather_stations=weather_stations.drop_duplicates()
weather_stations.head()

               STN     lat      lon
992   727675-94011  48.417 -101.350
1037  722164-53949  35.668  -95.949
1264  723146-53892  36.432  -81.419
1303  720539-00165  37.283 -107.050
1347  747804-13824  32.017  -81.133

In [12]:
output = pd.DataFrame()

for _,row in train.iterrows():
    C={"country":row["country"],"Distance":10000000}

    for _,row2 in weather_stations.iterrows():
        dist=(row["Lat"]-row2["lat"])**2+(row["Long"]-row2["lon"])**2
        if dist< C["Distance"]: 
            C={"country":row["country"],"STN":row2["STN"],"Distance":dist,"lat_st":row2["lat"],"long_st":row2["lon"]}

    output=output.append(C,ignore_index=True)

In [15]:
output.to_csv("matched_stations")
output.head()

      Distance           STN              country  lat_st  long_st
0  5493.418625  914080-40310          Afghanistan   7.367  134.544
1  7133.169839  789540-00408              Albania  13.067  -59.483
2  3962.425630  789540-00408              Algeria  13.067  -59.483
3  4588.258008  789540-00408              Andorra  13.067  -59.483
4     2.709325  788660-00399  Antigua and Barbuda  18.046  -63.115

In [14]:
weather_df['day_from_jan_first'] = (weather_df['da'].apply(int)
                                   + 31*(weather_df['mo']=='02') 
                                   + 60*(weather_df['mo']=='03')
                                   + 91*(weather_df['mo']=='04')
                                   + 121*(weather_df['mo']=='05')  
                                   + 152*(weather_df['mo']=='06')  
                                   + 182*(weather_df['mo']=='07')  
                                   + 213*(weather_df['mo']=='08')  
                                   + 244*(weather_df['mo']=='09')  
                                   + 274*(weather_df['mo']=='10')  
                                   + 305*(weather_df['mo']=='11')  
                                   + 335*(weather_df['mo']=='12'))

KeyError: 'day'

In [37]:
weather_df['day_from_jan_first'] = (weather_df['da']
                                       + 31*(weather_df['mo']==2) 
                                       + 60*(weather_df['mo']==3)
                                       + 91*(weather_df['mo']==4)
                                       + 121*(weather_df['mo']==5)  
                                       + 152*(weather_df['mo']==6)  
                                       + 182*(weather_df['mo']==7)  
                                       + 213*(weather_df['mo']==8)  
                                       + 244*(weather_df['mo']==9)  
                                       + 274*(weather_df['mo']==10)  
                                       + 305*(weather_df['mo']==11)  
                                       + 335*(weather_df['mo']==12))

In [38]:
weather_df[weather_df['STN'].isin(output["STN"])]
weather_df.head()

,Unnamed: 0,STN,mo,da,temp,min,max,stp,slp,dewp,wdsp,prcp,fog,call,lat,lon,elev,rh,ah,day_from_jan_first
992,992,727675-94011,6,29,67.1,65.7,69.8,939.2,998.2,66.6,8.3,0.91,1,KMIB,48.417,-101.350,508.1,0.982701,0.248996,181
1037,1037,722164-53949,1,11,39.1,31.5,48.6,985.4,NaN,39.1,14.8,0.57,1,KOKM,35.668,-95.949,219.5,1.000000,0.445230,11
1264,1264,723146-53892,2,7,40.2,24.6,50.4,886.0,NaN,37.9,10.8,0.00,1,KGEV,36.432,-81.419,969.3,0.913885,0.367770,38
1303,1303,720539-00165,3,19,34.4,28.4,45.5,761.6,NaN,29.8,7.4,99.99,1,KPSO,37.283,-107.050,2335.1,0.830644,0.908531,79
1320,1320,720539-00165,1,27,28.2,18.9,38.8,765.9,NaN,26.7,0.7,99.99,1,KPSO,37.283,-107.050,2335.1,0.940128,-0.505296,27

In [35]:
#weather_df=weather_df.drop(["country","state"],1)
335*(weather_df['mo']==1)

992          0
1037       335
1264         0
1303         0
1320       335
1347         0
1374         0
1418       335
1419       335
1420         0
1421         0
1422         0
1501       335
1504         0
1505       335
1506         0
1507         0
1509         0
1510         0
1511         0
1512         0
1513         0
1516         0
1517         0
1522         0
2944         0
2962         0
2985       335
2986         0
2987         0
          ...
2035552    335
2035553    335
2035554      0
2035555      0
2035556      0
2035557      0
2035558      0
2035559      0
2035560      0
2035561    335
2035562      0
2035563      0
2035565    335
2035566      0
2035567      0
2035568      0
2035569      0
2035572      0
2035573    335
2035574    335
2035575      0
2035576      0
2035577      0
2035578      0
2035579      0
2035580    335
2035581      0
2035582    335
2035583      0
2035584      0
Name: mo, Length: 311863, dtype: int32

In [39]:
weather_master=pd.merge(weather_df, output)
weather_master.head(200)

,Unnamed: 0,STN,mo,da,temp,min,max,stp,slp,dewp,...,lat,lon,elev,rh,ah,day_from_jan_first,Distance,country,lat_st,long_st
0,1419,724550-13947,1,10,34.4,24.6,41.7,975.7,NaN,27.2,...,39.050,-96.767,324.6,0.746709,0.816725,10,0.275588,US,39.050,-96.767
1,1506,724550-13947,4,20,58.6,46.6,72.9,972.6,1010.5,40.9,...,39.050,-96.767,324.6,0.515454,0.127481,111,0.275588,US,39.050,-96.767
2,1507,724550-13947,6,4,79.2,63.9,92.8,970.3,1007.3,68.7,...,39.050,-96.767,324.6,0.700291,0.199198,156,0.275588,US,39.050,-96.767
3,3197,724550-13947,4,17,38.3,32.9,50.9,982.1,1021.2,30.6,...,39.050,-96.767,324.6,0.735294,0.357553,108,0.275588,US,39.050,-96.767
4,136793,724550-13947,6,29,82.7,78.6,87.6,965.7,1002.3,71.9,...,39.050,-96.767,324.6,0.696544,0.207042,181,0.275588,US,39.050,-96.767
5,582987,724550-13947,2,22,39.3,30.9,58.3,983.9,1023.3,23.9,...,39.050,-96.767,324.6,0.536493,0.234144,53,0.275588,US,39.050,-96.767
6,629153,724550-13947,5,1,69.8,59.9,83.7,970.9,1009.2,49.5,...,39.050,-96.767,324.6,0.482030,0.124544,122,0.275588,US,39.050,-96.767
7,657961,724550-13947,1,6,31.2,20.1,50.2,984.3,1024.8,20.9,...,39.050,-96.767,324.6,0.652726,-1.883161,6,0.275588,US,39.050,-96.767
8,657962,724550-13947,1,9,52.0,45.0,56.1,969.4,1006.2,30.3,...,39.050,-96.767,324.6,0.430629,0.111265,9,0.275588,US,39.050,-96.767
9,657963,724550-13947,3,4,48.4,36.5,62.6,977.4,1015.8,26.8,...,39.050,-96.767,324.6,0.426823,0.117565,64,0.275588,US,39.050,-96.767
10,657964,724550-13947,3,31,55.5,41.7,69.6,979.6,1017.5,42.9,...,39.050,-96.767,324.6,0.623279,0.155904,91,0.275588,US,39.050,-96.767
11,657965,724550-13947,4,11,63.2,51.3,83.3,967.0,1004.9,37.7,...,39.050,-96.767,324.6,0.385845,0.095900,102,0.275588,US,39.050,-96.767
12,719821,724550-13947,1,4,35.0,18.9,48.6,983.8,1023.1,16.8,...,39.050,-96.767,324.6,0.470249,0.421440,4,0.275588,US,39.050,-96.767
13,719822,724550-13947,1,26,34.1,24.4,53.6,977.6,1017.0,28.7,...,39.050,-96.767,324.6,0.803735,0.992710,26,0.275588,US,39.050,-96.767
14,719823,724550-13947,2,21,27.0,12.4,47.5,997.0,1037.5,14.6,...,39.050,-96.767,324.6,0.591191,-0.229861,52,0.275588,US,39.050,-96.767
15,719824,724550-13947,2,29,44.5,22.8,71.2,981.1,1019.2,25.2,...,39.050,-96.767,324.6,0.463170,0.144354,60,0.275588,US,39.050,-96.767
16,719825,724550-13947,3,5,48.2,33.3,59.7,983.3,1022.2,20.9,...,39.050,-96.767,324.6,0.336026,0.092996,65,0.275588,US,39.050,-96.767
17,719826,724550-13947,3,25,57.3,45.7,78.1,971.0,1009.1,48.0,...,39.050,-96.767,324.6,0.708962,0.175878,85,0.275588,US,39.050,-96.767
18,719827,724550-13947,4,2,60.1,38.8,69.3,970.6,1008.2,45.5,...,39.050,-96.767,324.6,0.582919,0.144037,93,0.275588,US,39.050,-96.767
19,719828,724550-13947,4,10,43.5,23.4,63.0,982.2,1021.2,17.2,...,39.050,-96.767,324.6,0.343080,0.111853,101,0.275588,US,39.050,-96.767
20,719829,724550-13947,4,15,44.6,28.2,59.7,980.4,1019.2,19.5,...,39.050,-96.767,324.6,0.362977,0.112660,106,0.275588,US,39.050,-96.767
21,1255826,724550-13947,1,1,35.3,20.7,55.4,965.9,1007.2,23.9,...,39.050,-96.767,324.6,0.628187,0.517954,1,0.275588,US,39.050,-96.767
22,1255827,724550-13947,1,2,43.6,35.4,55.8,962.5,1000.5,34.2,...,39.050,-96.767,324.6,0.691907,0.224495,2,0.275588,US,39.050,-96.767
23,1255828,724550-13947,1,3,37.8,25.0,48.6,974.4,1013.1,28.2,...,39.050,-96.767,324.6,0.679925,0.352140,3,0.275588,US,39.050,-96.767
24,1255829,724550-13947,1,5,41.6,29.3,52.5,983.0,1021.9,24.3,...,39.050,-96.767,324.6,0.498819,0.181046,5,0.275588,US,39.050,-96.767
25,1255830,724550-13947,1,7,36.0,21.9,56.8,984.1,1023.8,20.5,...,39.050,-96.767,324.6,0.529443,0.370298,7,0.275588,US,39.050,-96.767
26,1255831,724550-13947,1,8,38.4,22.5,60.4,980.7,1020.0,22.6,...,39.050,-96.767,324.6,0.526272,0.252904,8,0.275588,US,39.050,-96.767
27,1255832,724550-13947,1,15,38.8,28.2,48.9,979.6,1018.5,34.2,...,39.050,-96.767,324.6,0.833538,0.382962,15,0.275588,US,39.050,-96.767
28,1255833,724550-13947,1,16,18.1,10.6,28.0,999.2,1040.5,5.1,...,39.050,-96.767,324.6,0.563145,-0.054169,16,0.275588,US,39.050,-96.767
29,1255834,724550-13947,1,19,21.8,15.8,34.3,995.0,1035.2,9.5,...,39.050,-96.767,324.6,0.586564,-0.089995,19,0.275588,US,39.050,-96.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,1982809,724550-13947,6,19,73.7,66.2,87.6,976.7,1013.9,65.6,...,39.050,-96.767,324.6,0.756117,0.202377,171,0.275588,US,39.050,-96.767
171,1982810,724550-13947,6,27,79.5,66.2,89.8,972.1,1009.0,68.3,...,39.050,-96.767,324.6,0.683799,0.195214,179,0.275588,US,39.050,-96.767
172,1982811,724550-13947,6,28,83.0,73.4,91.9,966.4,1003.2,72.3,...,39.050,-96.767,324.6,0.699225,0.208657,180,0.275588,US,39.050,-96.767
173,2029590,724550-13947,1,17,30.5,23.7,37.4,986.2,1026.4,24.1,...,39.050,-96.767,324.6,0.768277,-1.149063,17,0.275588,US,39.050,-96.767
174,2029591,724550-13947,1,22,35.7,33.6,39.2,976.4,1014.6,30.6,...,39.050,-96.767,324.6,0.814816,0.608806,22,0.275588,US,39.050,-96.767
175,2029592,724550-13947,1,23,36.6,33.8,37.8,974.0,1012.7,33.9,...,39.050,-96.767,324.6,0.898128,0.559366,23,0.275588,US,39.050,-96.767
176,2029593,724550-13947,1,30,36.5,33.8,39.7,981.7,1021.3,29.5,...,39.050,-96.767,324.6,0.754818,0.478660,30,0.275588,US,39.050,-96.767
177,2029594,724550-13947,2,5,27.4,24.3,31.6,979.3,1017.8,14.3,...,39.050,-96.767,324.6,0.573971,-0.246602,36,0.275588,US,39.050,-96.767
178,2029595,724550-13947,2,13,13.7,4.5,34.3,988.5,1028.6,0.6,...,39.050,-96.767,324.6,0.554074,-0.033457,44,0.275588,US,39.050,-96.767
179,2029596,724550-13947,2,25,36.5,28.8,48.4,976.5,1015.3,26.4,...,39.050,-96.767,324.6,0.664583,0.421438,56,0.275588,US,39.050,-96.767
180,2029597,724550-13947,4,3,32.5,26.4,43.0,982.5,1021.6,24.4,...,39.050,-96.767,324.6,0.717511,3.490625,94,0.275588,US,39.050,-96.767
181,1512,745310-93065,6,9,50.0,34.9,79.5,795.4,1008.7,32.4,...,38.967,-104.817,2003.2,0.505071,0.134593,161,0.252747,US,38.967,-104.817
182,3329,745310-93065,6,26,67.8,48.6,87.3,801.4,1012.4,43.9,...,38.967,-104.817,2003.2,0.417787,0.106349,178,0.252747,US,38.967,-104.817
183,721772,745310-93065,1,3,27.1,12.2,45.9,795.3,1017.7,9.4,...,38.967,-104.817,2003.2,0.468148,-0.186502,3,0.252747,US,38.967,-104.817
184,721773,745310-93065,1,4,35.0,23.0,56.1,800.3,1023.3,13.8,...,38.967,-104.817,2003.2,0.412801,0.369955,4,0.252747,US,38.967,-104.817
185,721774,745310-93065,1,5,39.8,29.1,49.3,801.5,1021.9,9.9,...,38.967,-104.817,2003.2,0.287627,0.119801,5,0.252747,US,38.967,-104.817
186,721775,745310-93065,1,6,31.6,17.8,41.5,800.2,1022.5,3.1,...,38.967,-104.817,2003.2,0.292952,-1.717952,6,0.252747,US,38.967,-104.817
187,721776,745310-93065,1,9,36.4,24.8,57.7,788.1,1004.4,4.8,...,38.967,-104.817,2003.2,0.261309,0.168803,9,0.252747,US,38.967,-104.817
188,721777,745310-93065,1,12,29.4,18.9,39.0,790.8,1011.4,3.1,...,38.967,-104.817,2003.2,0.320335,-0.264300,12,0.252747,US,38.967,-104.817
189,721778,745310-93065,1,19,24.3,10.4,42.3,806.3,1033.1,6.6,...,38.967,-104.817,2003.2,0.463696,-0.104666,19,0.252747,US,38.967,-104.817
190,721779,745310-93065,1,22,36.8,23.2,49.5,791.9,1010.3,16.7,...,38.967,-104.817,2003.2,0.435946,0.262266,22,0.252747,US,38.967,-104.817
191,721780,745310-93065,1,26,31.8,17.2,49.8,797.8,1018.8,15.0,...,38.967,-104.817,2003.2,0.494552,-5.847447,26,0.252747,US,38.967,-104.817
192,721781,745310-93065,2,15,32.9,22.3,47.7,794.9,1014.3,14.1,...,38.967,-104.817,2003.2,0.454914,1.249455,46,0.252747,US,38.967,-104.817
193,721782,745310-93065,2,16,32.8,20.1,48.6,793.7,1014.6,19.1,...,38.967,-104.817,2003.2,0.566816,1.744374,47,0.252747,US,38.967,-104.817
194,721783,745310-93065,2,29,42.2,28.4,55.0,798.0,1015.6,4.7,...,38.967,-104.817,2003.2,0.207327,0.072486,60,0.252747,US,38.967,-104.817
195,721784,745310-93065,3,3,35.8,20.5,53.2,792.2,1011.4,14.5,...,38.967,-104.817,2003.2,0.412283,0.301133,63,0.252747,US,38.967,-104.817
196,721785,745310-93065,3,18,46.7,30.2,61.3,792.2,1008.7,21.6,...,38.967,-104.817,2003.2,0.366310,0.105565,78,0.252747,US,38.967,-104.817
197,721786,745310-93065,3,26,50.2,33.6,65.3,788.4,1001.0,13.3,...,38.967,-104.817,2003.2,0.224686,0.059661,86,0.252747,US,38.967,-104.817
198,721787,745310-93065,4,7,55.6,37.0,70.9,796.1,1009.2,8.6,...,38.967,-104.817,2003.2,0.149460,0.037363,98,0.252747,US,38.967,-104.817
199,721788,745310-93065,4,11,54.7,30.9,66.9,790.3,1002.3,11.5,...,38.967,-104.817,2003.2,0.175729,0.044192,102,0.252747,US,38.967,-104.817

In [40]:
weather_master.groupby(['country']).size()

country
Afghanistan                   181
Albania                       181
Algeria                       181
Andorra                       181
Antigua and Barbuda           181
Argentina                     181
Armenia                       181
Aruba                         181
Australia                    1629
Austria                       181
Azerbaijan                    181
Bahrain                       181
Bangladesh                    181
Barbados                      181
Belarus                       181
Belgium                       181
Benin                         181
Bhutan                        181
Bolivia                       181
Bosnia and Herzegovina        181
Brazil                        181
Brunei                        181
Bulgaria                      181
Burkina Faso                  181
Cambodia                      181
Cameroon                      181
Canada                       1991
Central African Republic      181
Chile                         181
China                        5973
                            ...
Serbia                        181
Seychelles                    181
Singapore                     181
Slovakia                      181
Slovenia                      181
Somalia                       181
South Africa                  181
Spain                         181
Sri Lanka                     181
Sudan                         181
Suriname                      181
Sweden                        181
Switzerland                   181
Taiwan*                       181
Tanzania                      181
Thailand                      181
The Bahamas                   181
The Gambia                    181
Togo                          181
Trinidad and Tobago           181
Tunisia                       181
Turkey                        181
US                          10498
Ukraine                       181
United Arab Emirates          181
Uruguay                       181
Uzbekistan                    181
Venezuela                     181
Vietnam                       181
Zambia                        181
Length: 159, dtype: int64

In [41]:
weather_master.groupby('country').filter(lambda x : len(x)>181)["country"].unique()

array(['US', 'Canada', 'Australia', 'China'], dtype=object)

In [42]:
weather_master.to_csv("data/weather_master.csv")